<!-- SPDX-License-Identifier: Apache-2.0 -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Policy.Core/Policy.Core.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>
</Project>
